version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: timescaledb
      POSTGRES_USER: andrii
      POSTGRES_PASSWORD: myPass