<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <Version>0.11.0</Version>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>12.0</LangVersion>
        <Company>NBomber</Company>
        <Copyright>NBomber@2025</Copyright>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageIcon>nbomber_icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/PragmaticFlow/NBomber.Sinks.Timescale</RepositoryUrl>
        <PackageTags>load-testing, performance-testing, integration-testing, fsharp, timescale</PackageTags>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Description>NBomber sink that writes metrics data to TimescaleDB</Description>
        <Title>NBomber.Sinks.Timescale</Title>        
    </PropertyGroup>

	<PropertyGroup>		
		<NuGetAudit>true</NuGetAudit>		
		<NuGetAuditMode>all</NuGetAuditMode> <!-- Audit direct and transitive packages -->		
		<NuGetAuditLevel>low</NuGetAuditLevel> <!-- Report low, moderate, high and critical advisories -->
		<!-- Fails the build on CI or on release when a vulnerability is detected -->
		<WarningsAsErrors>(WarningsAsErrors);NU1900;NU1901;NU1902;NU1903;NU1904</WarningsAsErrors>
	</PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NBomber.Contracts" Version="6.2.0-beta.1" />
      <PackageReference Include="Npgsql" Version="9.0.3" />
      <PackageReference Include="RepoDb.PostgreSql" Version="1.13.1" />
      <PackageReference Include="RepoDb.PostgreSql.BulkOperations" Version="1.13.1" />
      <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" Visible="false" PackagePath="" />
        <None Include="../../assets/nbomber_icon.png" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="NBomber.Sinks.Timescale.Tests" />
        <InternalsVisibleTo Include="TimescaleBenchmark" />
        <InternalsVisibleTo Include="NBomber.Studio.WebAPI" />
        <InternalsVisibleTo Include="NBomber.Studio.Tests" />
    </ItemGroup>

</Project>
